#version 460 core

layout (local_size_x=4, local_size_y=4, local_size_z=4) in;

layout (binding=0, rgba16f) writeonly uniform image3D un_image0;
layout (binding=1, rgba16f) writeonly uniform image3D un_image1;
layout (binding=2, rgba16f) writeonly uniform image3D un_image2;

void main()
{
    ivec3 texel = ivec3(gl_GlobalInvocationID.xyz);
    imageStore(un_image0, texel, ivec4(0));
    imageStore(un_image1, texel, ivec4(0));
    // imageStore(un_image2, texel, vec4(0.0));
}
