#version 460 core
#extension GL_GOOGLE_include_directive: require

#include "./particle.glsl"

layout(
    local_size_x = 32,
    local_size_y = 1,
    local_size_z = 1
) in;


uniform uint un_offset;

void main()
{
    uint idx = un_offset + gl_LocalInvocationID.x;

    Particles[idx].t   = vec4(0.0);
    Particles[idx].sc  = vec4(1.0);
    Particles[idx].pos = vec4(0.0);
    Particles[idx].vel = vec4(0.0);
    Particles[idx].col = vec4(1.0, 0.0, 0.0, 1.0);

}

